"""add admin fields to user and listing

Revision ID: 26b5eee91594
Revises: 32ceec45067d
Create Date: 2026-05-06 13:34:49.950196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26b5eee91594'
down_revision = '32ceec45067d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_featured', sa.Boolean(), nullable=False, server_default=sa.text('0')))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('ban_status', sa.String(length=20), nullable=False, server_default='active'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('ban_status')
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.drop_column('is_featured')

    # ### end Alembic commands ###
