"""add message table and sold_at to listing

Revision ID: 32ceec45067d
Revises: a15915b6b18d
Create Date: 2026-04-25 19:58:27.881532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32ceec45067d'
down_revision = 'a15915b6b18d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index('ix_message_listing_created', ['listing_id', 'created_at'], unique=False)
        batch_op.create_index('ix_message_receiver_created', ['receiver_id', 'created_at'], unique=False)

    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sold_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.drop_column('sold_at')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index('ix_message_receiver_created')
        batch_op.drop_index('ix_message_listing_created')

    op.drop_table('message')
    # ### end Alembic commands ###
