"""add read_at to message

Revision ID: 464604cb0039
Revises: 26b5eee91594
Create Date: 2026-05-08 19:30:32.083299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '464604cb0039'
down_revision = '26b5eee91594'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read_at', sa.DateTime(), nullable=True))
        batch_op.create_index('ix_message_receiver_read', ['receiver_id', 'read_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index('ix_message_receiver_read')
        batch_op.drop_column('read_at')

    # ### end Alembic commands ###
