"""add login lockout columns to user

Revision ID: 740c57fee4b8
Revises: 26b5eee91594
Create Date: 2026-05-11 19:41:13.511476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '740c57fee4b8'
down_revision = '26b5eee91594'
branch_labels = None
depends_on = None


def upgrade():
    # server_default backfills 0 into existing rows so NOT NULL succeeds
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failed_login_attempts', sa.Integer(),
                                       nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('lockout_until', sa.DateTime(), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('lockout_until')
        batch_op.drop_column('failed_login_attempts')

    # ### end Alembic commands ###
